version: '3'

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.9.1
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      ZO_DATA_DIR: "data"
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD}
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5080
    volumes:
      - ./data/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true